### PR TITLE
[discussion] Tracking v0.6.y - not for merge

### PR DESCRIPTION
**Pull request by kakra**
@Zygo Since you are considering to tag a v0.6.1 version due to LOGICAL_INO_V2 memory usage, is this list of commits a good selection for a v0.6.1 tag?

I'd like to get in a fix for the gcc-8.2 build failure from issue #85. So I'm going to push one more commit soon.

### CODE REVIEW

**Comment by kakra** [comment]
@Zygo What do you think? Should we tag this as v0.6.1?

**Comment by Zygo** [comment]
This looks like a reasonable 0.6.1, except for the "serialize LOGICAL_INO" commit.  That one was experimental, it trades away performance, and the toxic extent detector improvement seems to do the same job better.  I would leave it out of stable branches until some more testing gets done on master.

**Comment by kakra** [comment]
Okay, done so. Do you want to transfer this branch over to your repo?

**Comment by kakra** [comment]
@Zygo Ping? Do you want to make this branch available officially in your repo or do you prefer if I maintain the backported branches in my repo?

I think it can be possible to let me push to specific branches in your repo directly if this is an option for you.

**Comment by Zygo** [comment]
Sorry, got distracted...

should there be tags too?

**Comment by kakra** [comment]
Gentoo downloads directly from Github tagged archives, so probably yes. :-)

Thanks for considering.

**Comment by Zygo** [comment]
Is this good now?  The branch and tag exist, but Github isn't auto-closing because we aren't merging this branch with `master`.

**Comment by kakra** [comment]
Yes, this is fine, I already submitted a new ebuild here:
https://github.com/gentoo/gentoo/pull/10439

Should we leave this open for further discussion until we declare v0.6.y EOL, or do you prefer to close this?

**Comment by Zygo** [comment]
I'd like to close PRs once a discrete goal is achieved.

We can open new ones as required when it's time for 0.6.2, 0.6.3, etc.  Or drop a note on commits like "this should be in 0.6.2".

Should there be a cadence, like "new stable once a week (if there's anything to push that week), new release every two months(ish)"?

**Comment by kakra** [comment]
I'm in for assembling a release every 1-2 months maybe without forcing it to be a v0.6.y or v0.7. That way we can get in some bug fixes fast without the experimental stuff, than finally at some time stabilize the experimental stuff as a more major version. I'll close this now.

**Pull request closed without merging**
