### PR TITLE
Skip nocow files to speed up processing

### PR DESCRIPTION
**Pull request by kakra**
If you have a lot of or a few big nocow files (like vm images) which
contain a lot of potential deduplication candidates, bees becomes
incredibly slow running through a lot "invalid operation" exceptions.

Let's just skip over such files to get more bang for the buck. I did no
regression testing as this patch seems trivial (and I cannot imagine any
pitfalls either). The process progresses much faster for me now.

### CODE REVIEW

**Comment by Zygo** [comment]
Last time I checked the kernel sources, the restriction was "src and dst must agree on whether the inode has datasums".  Since nodatacow implies nodatasum, this means it is not possible to dedup between a nodatacow file and a datacow file or vice versa; however, it should be possible to dedup a nodatacow file with another nodatacow file, and this patch would prevent such dedups.

Even if a nodatacow file is deduped with another nodatacow file, the result would seem to contradict the administrator's stated intent.  When blocks are deduped they become datacow regardless of mount options or inode attributes (they remain nodatasum though).  This suggests that we don't _want_ to dedup nodatacow files (especially those visibly marked with the NOCOW attribute), even when we _can_.

Also, if we want to dedup mixed extents (containing blocks of both dup and unique data) in nodatasum files, we have to create nodatasum temporary files.  This requires a second kind of tmp file (at least), and again it's not clear that we should do this even if we can.

I haven't been able to find a way to reliably detect whether nodatasum is in effect for a file, so bees has no such capability, so bees can't do the right thing; however, as this patch seems to address an important subset of nodatasum files, and the negative effects seem irrelevant, I will merge it (assuming no regressions pop up in testing over the next day or two).

**Comment by kakra** [comment]
Maybe it should be put on a todo list to make this configurable in the future. I'll keep my eyes open if we can detect the nodatasum case somehow. Personally, I'd be interested to coalesce my vm images again. They are only set nocow for performance and stability reasons: VirtualBox manages to freeze or damage the btrfs during io heavy workloads when the disk images are cow and not nocow. Also, performance decreases a lot over time (it is faster at starting with the disk image because cow files can be compressed).

**Comment by kakra** [comment]
I was thinking about this a bit...

I guess, if a file is nocow it implies that all its extents are nodatasum. Is the opposite also true? I.e. if a file is cow, all its extents are datasum, except the case when mount option nodatasum is set...

If yes, we could reliably detect this case and split hashes for the datasum and nodatasum case. The dedup algorithm would thus not try to mix both types of extents. Regarding my previous question: When mounted nodatasum, it implies datacow. It should imply no issues with "split-brain hashes".

What do you think? I could prepare a patch if you think it's doable and are interested.

**Comment by Zygo** [comment]
This is how I understand it:
```
nodatacow   nodatasum   does cow    does sum
---------   ---------   ---------   --------
no          no          yes         yes     
no          yes         yes         no      
yes         no          sometimes   no  
yes         yes         sometimes   no      
```

"sometimes" means snapshots and dedup, which still work and force datacow on for individual extents even if datacow is disabled.  Sums require CoW to work so they are disabled in all but the first case, and stay disabled.

AFAIK (I could be wrong on this), there's no reliable way to detect nodatasum.  Parsing /proc/mounts to find the options on the current mount point is fragile and error-prone, and I don't know of an ioctl that will give us the information.  Maybe /sys/fs/btrfs/<uuid>/<something> could expose that to userspace.  If you find (or implement) one, I'll be interested.

If a filesystem is mounted nodatasum or nodatacow, we can presume that 1) everything on the filesystem was created with that option (that's not necessarily true but it will be frequently true), and 2) any temp files bees creates will have matching sum/nosum extents (and therefore can be used for dedup).  So the mount options probably don't matter, bees should work as long as the filesystem hasn't been mounted for a while with one set and then mounted again with a different option set.

If anyone's patching anything, I'd prefer to just remove the five lines of kernel code that impose the restriction in the first place.  All extents are unambiguously datasum or nodatasum, and they don't change during dedup.  :-P

**Comment by kakra** [comment]
I'd say that the "sometimes" case doesn't change anything regarding datasums. It just allocates a new extents on write, that's cow behavior but not really cow. It happens just one time, successive writes to the new extents end up nocow again. The inode attribute on both affected files stays the same (and has to be the same as otherwise extents couldn't be shared in the first place).

So we should have a reliable way to detect the difference during dedup by just looking at the inode flag: different flags generate incompatible hashes, equal flags do.

I'm not sure what happens when I mount a file system with "nocow": Will it set nocow inode attribute on each file then? This would make detection of our use-case unreliable. But I think this is a totally strange use-case we could simply point to in the readme.

However, you pointed out one interesting clue about the temp files generated: A patch has to ensure to create this temp file with correct inode attributes before writing to the file.

I haven't looked at the code yet in detail (I still need to understand everything), but I'm pretty sure that such a detection should be easy to implement. The hash table would need one extra bit to tell which inode attributes the hash was generated from, so during dedup phase we filter for the appropriate flag. Maybe by sacrificing one bit from the hash dedicated to the inode flag, so we end up with different hashes for both types of inodes.

Maybe it would be a good idea to use xxhash then instead of crc, as it's said to be much faster. Of course this would make the hash table completely incompatible and one needs to start over. The idea comes from me seeing constantly high cpu usage (108%) during hashing with pretty low io transfer rates at the same time, while the extent rewriter achieves much much higher io rates. Is the hashing algorithm limiting us?

**Comment by Zygo** [comment]
Last time I checked, there is no inode flag for datasum visible from userspace to look at (userspace can see NOCOW_FL, but nothing for datasum which is what dedup cares about).  The dedup ioctl fails because it's looking at the _internal_ btrfs inode structure, which is full of fields that userspace can't see.

The mount options have nothing to do with the file flags (from the IOC_GETFLAGS ioctl).  The test in kernel code is something like "if this inode has NOCOW_FL set, or the filesystem is mounted nodatacow, and _this one extent_ is not shared, then write _this one extent_ in place."  So you can get files that are a mix of nodatacow and not nodatacow the same way you get files that are a mix of compressed and uncompressed, or summed and not summed.  It's precisely this sort of behavior that makes this so hard.

Last time I ran perf, it blamed TREE_SEARCH_V2 for most of the CPU time, followed by LOGICAL_INO.  It's probably searching the same inodes over and over (there's no caching of the TREE_SEARCH_V2 inside bees like there is for LOGICAL_INO).  CRC was way down the list, barely noticeable among the general kernel IO noise floor.

The IO subsystem needs a fair bit of work though--it does everything in units of 4K, sometimes reads backwards, and relies on VFS to handle shared blocks.  I'm planning on adding a replacement for VFS caching to address that, although it's not the top of the list as there seems to be more bang for the buck elsewhere.

**Comment by Zygo** [comment]
Some more thoughts...

We can identify nodatasum _extents_ fairly easily--just look up the extent bytenr in the csum tree, and the sums should be there or not.  This would allow the extents to be marked differently to avoid attempting to dedup them with the other kind of extent.  It's a little more complicated than that (e.g. when bees grows matching pairs of extents, the src might spill over onto differently-summed extents) but still doable.  This case comes up for toxic extents too, although in the toxic extent case we just throw the exception and move on, while in the nodatasum case we would need to stop growing and continue with the dedup.

The temporary file class could just have two instances, one for datasum extents, one for non-datasum extents, and the extent rewriter could use the appropriate one for a match.

Meh, or we just patch the kernel to allow these dedups.  But then again it might be the right thing to do to support the two kinds of extent as separate duplicate classes.  I keep going back and forth on this.



Bees reserves the bottom 12 bits of physical addresses in the hash table for various flags:  6 bits for compressed offsets, 1 for compression, 1 for unaligned EOF.  That leaves 3 more.  Lots of bits are 0 in btrfs physical addresses because they're byte offsets on a filesystem with at least a 4K block size (so the bottom 12 bits are effectively always 0, as well as several at the top).  There's no need to steal bits from the hash yet.

If we read the checksums directly out of the checksum tree, we can use them instead of reading and hashing blocks.  32 bits is too short for a hash--the collision rate after 16TB of unique data is too high, about 48-54 bytes are required for filesystems up to ~100TB; however, two consecutive 4K block CRC32s can be catenated to make a 64-bit hash, and that _is_ long enough.  If done correctly, bees won't need to read files at all while scanning them, only the reads during compare and dedup will be required.  We'd lose some efficiency on compressed files, but I think the current design which tries to chop up compressed extents into smaller dedupable pieces isn't saving as much space as I'd like for the time it takes.




> while the extent rewriter achieves much much higher io rates

Note that the extent rewriter almost always re-reads something that was very recently read by the scanner, so the data will still be in the VFS page cache (unless you are _really_ low on memory).  Extent rewrite typically has near-zero read overhead because the scanner does all the heavy lifting on reads, and the writes from dedup tend to get paid for by LOGICAL_INO and TREE_SEARCH_V2 requests that follow (or any other ioctl on the filesystem that joins a transaction and thereby waits for a commit and/or flush).

I am planning to do a rewrite that caches more stuff on reads and defers more writes to dedicated threads, partly to improve IO performance, but mostly to avoid bisecting extents almost all the time.

**Comment by kakra** [comment]
> If we read the checksums directly out of the checksum tree, we can use them instead of reading and hashing blocks. 32 bits is too short for a hash--the collision rate after 16TB of unique data is too high, about 48-54 bytes are required for filesystems up to ~100TB; however, two consecutive 4K block CRC32s can be catenated to make a 64-bit hash, and that is long enough. If done correctly, bees won't need to read files at all while scanning them, only the reads during compare and dedup will be required. We'd lose some efficiency on compressed files, but I think the current design which tries to chop up compressed extents into smaller dedupable pieces isn't saving as much space as I'd like for the time it takes.

This stops us from deduping nodatasum extents at all, doesn't it? So we'd still need to read such extents manually and generate hashes then.

**Comment by Zygo** [comment]
Yes, there would have to be some kind of fallback to internal sum generation to dedup when there are no-sum extents.

I think if we use TREE_SEARCH_V2 to test for sums, we have to read the sums into bees memory anyway, so we might as well do something useful with them.  If the order was read-subvol-tree then read-csum-tree and we get csums, we can skip the block reads; otherwise, we proceed to read the blocks and generate sums.

**Comment by kakra** [comment]
I think this would be great. Does this also mean that the minimum dedup size will be 8k then because we are concatenating two btrfs csums? This would be closer to the 12k minimum idea you outlined in the README, and it's faster anyways so that point could be cleared.

**Comment by Zygo** [comment]
The block size could still be 4K, just overlap the blocks (i.e. the DDT entries are (sum block 1, sum block 2), (sum block 2, sum block 3), (sum block 3, sum block 4), ...).  We don't want to increase the alignment constraint or we lose the ability to dedup well inside VM images (we find only the half of the blocks that happen to match on 8K boundaries).  Once we've found a pair of matching 4K-aligned 8K-length blocks, the alignment offset and extent boundaries are known, and we can use larger IO sizes for the final dedup.

Speaking of alignment, another drawback (and the killer reason why I haven't pursued reading the csum tree directly so far) is that we lose the ability to dedup compressed extents well.  This is because the csums apply to the compressed data, not the uncompressed data.  Uncompressed data and compressed data would have different csums.  That's OK if your filesystem has a lot of e.g. unpacked source trees with lots of single-extent compressed files, but that's pretty much the only case that still works.  One particular case that doesn't work is "log file vs.  copy of the same log file" because the different writing patterns change the compressed extent boundaries, so the sums don't match when the data is identical.

On the other hand if you don't use compression then the drawback doesn't apply.  All you lose is then is the ability to dedup 4K extents, and that's usually less than 1% of the total filesystem size.

I have a very different plan to deal with the performance of small (&lt;12K) extents:  batch them up into bigger extents in the extent rewriter so that they're not small any more.  This effectively turns bees into a unified defrag+dedup tool, and counteracts the tendency for average extent size to get smaller as bees runs.

**Comment by Zygo** [comment]
Update after a read of the kernel sources and some tests:

btrfs decides whether to read checksums or not by looking at the (hidden) NODATASUM inode flag.  The 'nodatasum' mount option controls whether newly created files get this flag (and nodatacow determines the NODATASUM/NOCOW_FL flag state).  That means once a file has been created, it's nodatasum or datasum (determined at creation time by the mount options) forever, regardless of what mount options are used in the future.  There is one good reason for this:  when we are reading files via the inode (the obviously common case, i.e. the POSIX read() function), we want to know if we have csums to verify without having to do the csum tree lookup every time.  It's a bit messier for the relocation code (which starts from the extent and has to look up an inode much like bees does) but that's a less common case so it makes sense to be more awkward.

That means we should _not_ patch the kernel, i.e. the restriction serves a useful purpose.  bees needs to deal with this case.

Bees can read the NODATASUM flag directly from the btrfs inode, bypassing the GETFLAGS ioctl.  bees already gets the raw inode data--it's the INODE_ITEM in the TREE_SEARCH_V2 results.  We can't avoid reading those in the crawler, bees currently just throws the data away.

A NODATACOW file seems to be usable as a source file for a NODATASUM target in the extent rewriter.  This would enable us to generate the two kinds of temp files required.  The nodatasum flag can be turned off on empty files by clearing the NOCOW_FL flag with IOC_SETFLAGS, or turned on by setting the flag.

I merged the earlier patch for now, until a more complete solution can be developed.  Are you up for making this change?

**Comment by kakra** [comment]
While I've done a lot OOP and C programming in the past, I'm not yet very familiar with a the modern C++ stuff but I can dig my way through it. I can try preparing patches for you to review. I still need to understand the execution flows in your code.

I'd start with the easier ones. Maybe you could make some issues in the issue tracker and use Github projects to assign them to junior jobs? ;-)

I'm going to have some more time next month or the month after to dig deeper.

BTW: I very much like the defragging approach you are planning.

**Pull request merged**
