### PR TITLE
Suggest tagging of v0.6.2: Hotfixes for compile failures

### PR DESCRIPTION
**Pull request by kakra**
@Zygo I suggest to tag this as v0.6.2. At least Gentoo is waiting on getting these bug fixed, it currently blocks upgrades to gcc 9.2 and glibc 2.30 without these fixes.

Actually, the `gittid()` fix is not yet pulled into your master, you may want to do that first.

Meanwhile, I will use that as an interims patchset to the Gentoo v0.6.1 build. But it would be nice to have it tagged officially. Thanks.

I'd prefer holding this PR back for now, until your merge of #128 into master.

Closes: #122
CC: @Kriskras99

### CODE REVIEW

**Comment by kakra** [comment]
@Zygo I cherry-picked a few more commits which I think are worth pulling into a patch release. What do you think?

**Comment by Zygo** [comment]
It also needs 866a35c.

I'm wondering if it would be better to just fix any outstanding issues and drop a 7.0 release.  AFAIK the only outstanding issue that isn't a feature request, support question, or kernel bug is #120 and that's probably easier to fix than to figure out which commits we need to backport to 0.6.2.

The last commit was a year ago, I think we've done a long enough soak for a full release.  ;)

**Comment by kakra** [comment]
Thus be it whatever tag hits the repository first - I'm fine with both.

**Comment by Zygo** [comment]
Commit cdca2bcdcde7c0decf5f0553d37a811a677a4aa8 is missing.  Crash on startup without it.

I have master and v0.6.y branch updates which seem to work (for the 30 seconds of testing I've been able to do...).

Let me know if these are good or if I've messed something up.  If they seem to solve more issues than they raise then I'll tag them.

**Comment by kakra** [comment]
After rebase and force-push, I see that all commits are in v0.6.y already. Time to tag?

**Pull request closed without merging**
