### PR TITLE
Some cleanups from my integration branch

### PR DESCRIPTION
**Pull request by kakra**
@Zygo Here are a few patches left over in my integration branch. Not sure if I missed to push them or if you deliberately didn't merge them. Feel free to reject in the latter case. ;-)

### CODE REVIEW

**Comment by kakra** [comment]
I added a few more you may want to merge.

Thanks.

**Comment by kakra** [comment]
@Nefelim4ag This may affect your Arch packaging. Would you like to review?

**Comment by Nefelim4ag** [comment]
@kakra, i test you branch in packaging, no obvious problems, thanks.

**Comment by kakra** [comment]
@Nefelim4ag I think that last commit is important for you because I seem to have unintentionally reverted a previous fixup by you. Could you check?

**Comment by Nefelim4ag** [comment]
@kakra, thanks, tested again, no obvious problems

**Comment by kakra** [comment]
After rebasing my local branches, this seems to be applied. Closing.

Thanks.

**Pull request closed without merging**
