### PR TITLE
FIX: The systemd service file is always installed

### PR DESCRIPTION
**Pull request by nilninull**

### CODE REVIEW

**Comment by kakra** [comment]
If you're using Gentoo, the systemd unit file should be installed no matter if systemd is part of the system or not. But I need to change the ebuild to do that correctly (Gentoo has an eclass to solve this correctly which would also remove systemd as a build time dependency). Thanks for the fix. LGTM.

**Comment by Zygo** [comment]
@kakra Should I pull this, or will you include this change in a larger fix?

**Comment by kakra** [comment]
Pull... It's a local and correct fix in bees. The rest will go into Gentoo portage (or other downstreams), nothing else related here.

**Comment by Zygo** [comment]
Done.  Thanks.

**Pull request merged**
